// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {Descriptor} from "../../src/Descriptor.sol";
import {DescriptorData} from "../../src/gen/DescriptorData.sol";
import {SSTORE2} from "../../src/lib/SSTORE2.sol";

/// Deploys the REAL Descriptor from the encoded art pages in
/// script/descriptor-data (generated by tools/art/encode_descriptor.py from
/// the Step 0 pixel-proof manifest). The Descriptor constructor pins every
/// page by code hash, so a stale or tampered hex file cannot construct.
abstract contract DescriptorFixture is Test {
    Descriptor internal descriptor;
    address[] internal artPages;
    address[] internal piecePages;
    address internal metaPage;

    function _deployDescriptor() internal {
        for (uint256 i = 0; i < DescriptorData.ART_PAGE_COUNT; i++) {
            artPages.push(SSTORE2.write(_pageData("art-page-", i)));
        }
        for (uint256 i = 0; i < DescriptorData.PIECE_PAGE_COUNT; i++) {
            piecePages.push(SSTORE2.write(_pageData("piece-page-", i)));
        }
        metaPage = SSTORE2.write(_pageData("meta-page-", 0));
        descriptor = new Descriptor(artPages, piecePages, metaPage);
    }

    function _pageData(string memory prefix, uint256 i)
        internal
        view
        returns (bytes memory)
    {
        return vm.parseBytes(
            string.concat(
                "0x",
                vm.readFile(
                    string.concat(
                        "script/descriptor-data/", prefix, vm.toString(i), ".hex"
                    )
                )
            )
        );
    }
}
